name: Publish GitHub Pages

on:
  push:
    branches:
      - master
      - add-demo

jobs:
  publish_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Build parent package
        run:
          npm ci
          pm run build
      - name: Build demo page
        working-directory: ./demo
        run: |
          npm ci
          npm run build
          npm run export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/out
